# Generated by Django 2.1.15 on 2021-11-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemCFrecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=15)),
                ('asin', models.CharField(max_length=15)),
                ('rating', models.IntegerField()),
                ('imageURL', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
