# Generated by Django 2.1.15 on 2021-11-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaweb', '0003_auto_20211118_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBrecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=15)),
                ('asin_rec', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('imageURL', models.CharField(max_length=200)),
            ],
        ),
    ]
